"use node";

import { v } from "convex/values";
import { action } from "./_generated/server";
import { api } from "./_generated/api";
import { Resend } from "resend";

/**
 * Send a verification email to a user
 *
 * This is an action that runs in a Node.js environment to use the Resend API.
 * It sends a beautifully formatted HTML email with a verification link.
 *
 * **Environment Variables Required**:
 * - RESEND_API_KEY: API key for Resend email service
 * - SITE_URL: Base URL of the application (e.g., "https://quotable.app")
 *
 * **Email Template**:
 * - Professional gradient header
 * - Clear call-to-action button
 * - Fallback text link
 * - Responsive design
 * - 24-hour expiry notice
 *
 * @param args.userId - The user's database ID
 * @param args.token - The verification token generated by generateVerificationToken
 * @returns Object with success status, message, and Resend email ID
 *
 * @example
 * ```typescript
 * const result = await ctx.runAction(api.emailVerificationActions.sendVerificationEmail, {
 *   userId: user._id,
 *   token: "a1b2c3d4e5f6..."
 * });
 *
 * if (result.success) {
 *   console.log(`Email sent: ${result.emailId}`);
 * }
 * ```
 *
 * **Error Handling**:
 * - Missing API key: Throws error with setup instructions
 * - Missing SITE_URL: Throws error with configuration guidance
 * - Email send failure: Throws error with Resend error details
 * - Invalid user: Throws error if user not found
 *
 * @see {@link https://resend.com/docs | Resend Documentation}
 * @see {@link https://resend.com/docs/send-with-nodejs | Resend Node.js Guide}
 * @see {@link generateVerificationToken} To create a verification token
 * @see {@link verifyEmail} To validate the token
 */
export const sendVerificationEmail = action({
  args: {
    userId: v.id("users"),
    token: v.string(),
  },
  handler: async (ctx, args) => {
    // Get user details
    const user = await ctx.runQuery(api.users.getCurrentUser, {});

    if (!user) {
      throw new Error("User not found");
    }

    if (!user.email) {
      throw new Error("User email not found");
    }

    // Store email for type safety (TypeScript type narrowing)
    const userEmail: string = user.email;

    // Validate required environment variables
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) {
      throw new Error("RESEND_API_KEY environment variable not set. Please add it to Convex Dashboard > Settings > Environment Variables.");
    }

    const siteUrl = process.env.SITE_URL;
    if (!siteUrl) {
      throw new Error("SITE_URL environment variable not set. Please add it to Convex Dashboard > Settings > Environment Variables.");
    }

    // Construct verification link
    const verificationLink = `${siteUrl}/verify-email?token=${args.token}`;

    // Initialize Resend
    const resend = new Resend(apiKey);

    try {
      // Send verification email
      const { data, error } = await resend.emails.send({
        from: "So Quotable <onboarding@resend.dev>",
        to: [userEmail],
        subject: "Verify your email address - So Quotable",
        html: `
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Verify your email</title>
            </head>
            <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                <h1 style="color: white; margin: 0; font-size: 28px;">So Quotable</h1>
              </div>
              <div style="background: #ffffff; padding: 40px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 10px 10px;">
                <h2 style="color: #333; margin-top: 0;">Hello ${user.name},</h2>
                <p style="font-size: 16px; color: #555;">Thank you for signing up for So Quotable! To get started, please verify your email address by clicking the button below:</p>
                <div style="text-align: center; margin: 35px 0;">
                  <a href="${verificationLink}" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 40px; text-decoration: none; border-radius: 5px; font-weight: bold; font-size: 16px; display: inline-block;">Verify Email Address</a>
                </div>
                <p style="font-size: 14px; color: #777; margin-top: 30px;">
                  This verification link will expire in <strong>24 hours</strong>. If you didn't create an account with So Quotable, you can safely ignore this email.
                </p>
                <p style="font-size: 14px; color: #777; margin-top: 20px;">
                  If the button doesn't work, copy and paste this link into your browser:<br>
                  <a href="${verificationLink}" style="color: #667eea; word-break: break-all;">${verificationLink}</a>
                </p>
                <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 30px 0;">
                <p style="font-size: 12px; color: #999; text-align: center;">
                  © ${new Date().getFullYear()} So Quotable. All rights reserved.
                </p>
              </div>
            </body>
          </html>
        `,
      });

      if (error) {
        console.error("Resend error:", error);
        throw new Error(`Failed to send verification email: ${error.message}`);
      }

      console.log(`✅ Verification email sent successfully to ${user.email} (Resend ID: ${data?.id})`);

      return {
        success: true,
        message: "Verification email sent successfully",
        emailId: data?.id,
      };
    } catch (error) {
      console.error("Error sending verification email:", error);
      throw new Error(`Failed to send verification email: ${error instanceof Error ? error.message : "Unknown error"}`);
    }
  },
});
